---
- name: Download AWS CLI 2 Installer
  unarchive:
    src: "{{ aws_cli_download_url }}"
    dest: "/tmp"
    remote_src: true
    creates: '/tmp/aws'
    mode: 0755

- name: Run install
  command:
    cmd: /tmp/aws/install
    creates: /usr/local/bin/aws
  become: true
