---
galaxy_info:
  role_name: brave
  description: Install Brave browser
  author: blowupshappen
  license: license (MIT)
  min_ansible_version: 2.9
  platforms:
    - name: CentOS
      versions:
        - 8

dependencies: []
