---
vscode_site: https://packages.microsoft.com
vscode_extensions:
  - VisualStudioExptTeam.vscodeintellicode
  - vscoss.vscode-ansible
  - redhat.vscode-yaml
  - samuelcolvin.jinjahtml
  - RobbOwen.synthwave-vscode
  - eamodio.gitlens

vscode_settings:
  editor.tabSize: 2
  editor.insertSpaces: true
